import { getSyncedSnapshot } from '../intelligence/sync.js'

export interface ModelSpec {
  id: string
  provider: string
  contextWindow: number
  maxOutputTokens: number
  minOutputTokens?: number
  thinkingBudgetCap?: number
  defaultThinkingBudget?: number
  supportsVision?: boolean
  supportsThinking?: boolean
  supportedParams: Set<string>
  stripParams: Set<string>
  requiresThinkingReconciliation: boolean
}

export const MODEL_REGISTRY: Record<string, ModelSpec> = {
  'anthropic/claude-fable-5': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-fable-5',
    provider: 'anthropic',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 120000,
    defaultThinkingBudget: 32000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-opus-4-5': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-opus-4-5',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    thinkingBudgetCap: 32000,
    defaultThinkingBudget: 10000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-opus-4-5-20251101': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-opus-4-5-20251101',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    thinkingBudgetCap: 32000,
    defaultThinkingBudget: 10000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-opus-4-6': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-opus-4-6',
    provider: 'anthropic',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 120000,
    defaultThinkingBudget: 32000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-opus-4-7': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-opus-4-7',
    provider: 'anthropic',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 120000,
    defaultThinkingBudget: 32000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-opus-4-8': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-opus-4-8',
    provider: 'anthropic',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 120000,
    defaultThinkingBudget: 32000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-opus-5': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-opus-5',
    provider: 'anthropic',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 120000,
    defaultThinkingBudget: 32000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-sonnet-4-5': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-sonnet-4-5',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    thinkingBudgetCap: 62000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-sonnet-4-6': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-sonnet-4-6',
    provider: 'anthropic',
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    thinkingBudgetCap: 62000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'anthropic/claude-sonnet-5': {
    // source: fixed missing maxOutputTokens
    id: 'anthropic/claude-sonnet-5',
    provider: 'anthropic',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 120000,
    defaultThinkingBudget: 32000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'bedrock/anthropic.claude-fable-5': {
    // source: modelSpecs.ts:369 claude-fable-5
    id: 'bedrock/anthropic.claude-fable-5',
    provider: 'bedrock',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 120000,
    defaultThinkingBudget: 32000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'bedrock/anthropic.claude-haiku-4-5': {
    // source: fixed missing maxOutputTokens
    id: 'bedrock/anthropic.claude-haiku-4-5',
    provider: 'bedrock',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'bedrock/anthropic.claude-opus-4-6': {
    // source: fixed missing maxOutputTokens
    id: 'bedrock/anthropic.claude-opus-4-6',
    provider: 'bedrock',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'bedrock/anthropic.claude-opus-4-7': {
    // source: fixed missing maxOutputTokens
    id: 'bedrock/anthropic.claude-opus-4-7',
    provider: 'bedrock',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'bedrock/anthropic.claude-sonnet-4-5': {
    // source: fixed missing maxOutputTokens
    id: 'bedrock/anthropic.claude-sonnet-4-5',
    provider: 'bedrock',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'bedrock/openai.gpt-oss-120b-1:0': {
    // source: fixed missing maxOutputTokens
    id: 'bedrock/openai.gpt-oss-120b-1:0',
    provider: 'bedrock',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'commandcode/deepseek/deepseek-v4-flash': {
    // source: fixed missing maxOutputTokens
    id: 'commandcode/deepseek/deepseek-v4-flash',
    provider: 'commandcode',
    contextWindow: 262144,
    maxOutputTokens: 200000,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(['temperature', 'top_p']),
    requiresThinkingReconciliation: false,
  },
  'commandcode/gpt-5.6-luna': {
    // source: fixed missing maxOutputTokens
    id: 'commandcode/gpt-5.6-luna',
    provider: 'commandcode',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'deepseek/deepseek-v4-flash': {
    // source: fixed missing maxOutputTokens
    id: 'deepseek/deepseek-v4-flash',
    provider: 'deepseek',
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    thinkingBudgetCap: 380000,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'deepseek/deepseek-v4-pro': {
    // source: modelSpecs.ts:647 deepseek-v4-pro (384000/1000000 cap380000)
    id: 'deepseek/deepseek-v4-pro',
    provider: 'deepseek',
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    thinkingBudgetCap: 380000,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'gemini-3.7-flash-tiered': {
    // source: fixed missing maxOutputTokens
    id: 'gemini-3.7-flash-tiered',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    thinkingBudgetCap: 24576,
    defaultThinkingBudget: 8192,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-2.5-flash': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-2.5-flash',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    thinkingBudgetCap: 24576,
    supportsVision: true,
    supportsThinking: false,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-3.6-flash-high': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-3.6-flash-high',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    supportsVision: true,
    supportsThinking: false,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-3.6-flash-low': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-3.6-flash-low',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    supportsVision: true,
    supportsThinking: false,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-3.6-flash-medium': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-3.6-flash-medium',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    supportsVision: true,
    supportsThinking: false,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-3.7-flash': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-3.7-flash',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    thinkingBudgetCap: 24576,
    defaultThinkingBudget: 8192,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-3.7-flash-high': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-3.7-flash-high',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    thinkingBudgetCap: 24576,
    defaultThinkingBudget: 24576,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-3.7-flash-low': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-3.7-flash-low',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    thinkingBudgetCap: 24576,
    defaultThinkingBudget: 1024,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-3.7-flash-medium': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-3.7-flash-medium',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    thinkingBudgetCap: 24576,
    defaultThinkingBudget: 8192,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'gemini/gemini-3.7-flash-tiered': {
    // source: fixed missing maxOutputTokens
    id: 'gemini/gemini-3.7-flash-tiered',
    provider: 'gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    thinkingBudgetCap: 24576,
    defaultThinkingBudget: 8192,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  k3: {
    // source: modelSpecs.ts:437 kimi-k3 (1048576/1048576 cap32768) alias k3
    id: 'k3',
    provider: 'moonshot',
    contextWindow: 1048576,
    maxOutputTokens: 1048576,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'kimi-k2.5-thinking': {
    // source: fixed missing maxOutputTokens
    id: 'kimi-k2.5-thinking',
    provider: 'moonshot',
    contextWindow: 262144,
    maxOutputTokens: 262144,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'kimi-k2.6-thinking': {
    // source: fixed missing maxOutputTokens
    id: 'kimi-k2.6-thinking',
    provider: 'moonshot',
    contextWindow: 262144,
    maxOutputTokens: 262144,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'kimi-k2.7': {
    // source: fixed missing maxOutputTokens
    id: 'kimi-k2.7',
    provider: 'moonshot',
    contextWindow: 262144,
    maxOutputTokens: 262144,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'kimi-k2.7-code-highspeed': {
    // source: fixed missing maxOutputTokens
    id: 'kimi-k2.7-code-highspeed',
    provider: 'moonshot',
    contextWindow: 262144,
    maxOutputTokens: 262144,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'kimi-k2.7-code-thinking': {
    // source: fixed missing maxOutputTokens
    id: 'kimi-k2.7-code-thinking',
    provider: 'moonshot',
    contextWindow: 262144,
    maxOutputTokens: 262144,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'MiniMax-M2.5': {
    // source: fixed missing maxOutputTokens
    id: 'MiniMax-M2.5',
    provider: 'minimax',
    contextWindow: 200000,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 32768,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'MiniMax-M2.7': {
    // source: fixed missing maxOutputTokens
    id: 'MiniMax-M2.7',
    provider: 'minimax',
    contextWindow: 204800,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 32768,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'MiniMax-M3': {
    // source: fixed missing maxOutputTokens
    id: 'MiniMax-M3',
    provider: 'minimax',
    contextWindow: 1048576,
    maxOutputTokens: 512000,
    thinkingBudgetCap: 32768,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'minimax/minimax-m2.5': {
    // source: fixed missing maxOutputTokens
    id: 'minimax/minimax-m2.5',
    provider: 'minimax',
    contextWindow: 200000,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 32768,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'minimax/MiniMax-M2.5-highspeed': {
    // source: fixed missing maxOutputTokens
    id: 'minimax/MiniMax-M2.5-highspeed',
    provider: 'minimax',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'minimax/minimax-m2.7': {
    // source: fixed missing maxOutputTokens
    id: 'minimax/minimax-m2.7',
    provider: 'minimax',
    contextWindow: 204800,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 32768,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'minimax/MiniMax-M2.7-highspeed': {
    // source: fixed missing maxOutputTokens
    id: 'minimax/MiniMax-M2.7-highspeed',
    provider: 'minimax',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'minimax/minimax-m3': {
    // source: modelSpecs.ts:619 minimax-m3 (512000/1048576 cap32768)
    id: 'minimax/minimax-m3',
    provider: 'minimax',
    contextWindow: 1048576,
    maxOutputTokens: 512000,
    thinkingBudgetCap: 32768,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'moonshot/kimi-k2.5': {
    // source: fixed missing maxOutputTokens
    id: 'moonshot/kimi-k2.5',
    provider: 'moonshot',
    contextWindow: 262144,
    maxOutputTokens: 262144,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'moonshot/kimi-k2.6': {
    // source: fixed missing maxOutputTokens
    id: 'moonshot/kimi-k2.6',
    provider: 'moonshot',
    contextWindow: 262144,
    maxOutputTokens: 262144,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'moonshot/kimi-k2.7-code': {
    // source: fixed missing maxOutputTokens
    id: 'moonshot/kimi-k2.7-code',
    provider: 'moonshot',
    contextWindow: 262144,
    maxOutputTokens: 262144,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'moonshot/kimi-k3': {
    // source: modelSpecs.ts:437 kimi-k3 (1048576/1048576)
    id: 'moonshot/kimi-k3',
    provider: 'moonshot',
    contextWindow: 1048576,
    maxOutputTokens: 1048576,
    thinkingBudgetCap: 32768,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'openai/gpt-4o': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-4o',
    provider: 'openai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportsVision: true,
    supportsThinking: false,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'openai/gpt-4o-mini': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-4o-mini',
    provider: 'openai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportsVision: true,
    supportsThinking: false,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>([
      'temperature',
      'top_p',
      'frequency_penalty',
      'presence_penalty',
      'logprobs',
      'top_logprobs',
      'n',
    ]),
    requiresThinkingReconciliation: true,
  },
  'openai/gpt-5.4': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-5.4',
    provider: 'openai',
    contextWindow: 409600,
    maxOutputTokens: 131072,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'openai/gpt-5.4-pro': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-5.4-pro',
    provider: 'openai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'openai/gpt-5.5': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-5.5',
    provider: 'openai',
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'openai/gpt-5.5-pro': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-5.5-pro',
    provider: 'openai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'openai/gpt-5.6': {
    // source: modelSpecs.ts:90 GPT_5_6_MODEL_SPEC (1050000/128000 cap96000)
    id: 'openai/gpt-5.6',
    provider: 'openai',
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 96000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'openai/gpt-5.6-luna': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-5.6-luna',
    provider: 'openai',
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 96000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'openai/gpt-5.6-sol': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-5.6-sol',
    provider: 'openai',
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 96000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'openai/gpt-5.6-terra': {
    // source: fixed missing maxOutputTokens
    id: 'openai/gpt-5.6-terra',
    provider: 'openai',
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 96000,
    supportsVision: true,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'opencode/big-pickle': {
    // source: fixed missing maxOutputTokens
    id: 'opencode/big-pickle',
    provider: 'opencode',
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'opencode/hy3-free': {
    // source: fixed missing maxOutputTokens
    id: 'opencode/hy3-free',
    provider: 'opencode',
    contextWindow: 262144,
    maxOutputTokens: 32768,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'opencode/laguna-s-2.1-free': {
    // source: fixed missing maxOutputTokens
    id: 'opencode/laguna-s-2.1-free',
    provider: 'opencode',
    contextWindow: 262144,
    maxOutputTokens: 65536,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'opencode/mimo-v2.5-free': {
    // source: fixed missing maxOutputTokens
    id: 'opencode/mimo-v2.5-free',
    provider: 'opencode',
    contextWindow: 262144,
    maxOutputTokens: 65536,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'opencode/muse-spark-1.2-contributor-free': {
    // source: fixed missing maxOutputTokens
    id: 'opencode/muse-spark-1.2-contributor-free',
    provider: 'opencode',
    contextWindow: 131072,
    maxOutputTokens: 32768,
    minOutputTokens: 512,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'opencode/x-preview-f-free': {
    // source: fixed missing maxOutputTokens
    id: 'opencode/x-preview-f-free',
    provider: 'opencode',
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'xiaomi-mimo/mimo-v2-flash': {
    // source: fixed missing maxOutputTokens
    id: 'xiaomi-mimo/mimo-v2-flash',
    provider: 'xiaomi-mimo',
    contextWindow: 262144,
    maxOutputTokens: 65536,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'xiaomi-mimo/mimo-v2-omni': {
    // source: fixed missing maxOutputTokens
    id: 'xiaomi-mimo/mimo-v2-omni',
    provider: 'xiaomi-mimo',
    contextWindow: 262144,
    maxOutputTokens: 131072,
    supportsVision: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'xiaomi-mimo/mimo-v2-pro': {
    // source: fixed missing maxOutputTokens
    id: 'xiaomi-mimo/mimo-v2-pro',
    provider: 'xiaomi-mimo',
    contextWindow: 262144,
    maxOutputTokens: 131072,
    supportsVision: false,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'xiaomi-mimo/mimo-v2.5': {
    // source: fixed missing maxOutputTokens
    id: 'xiaomi-mimo/mimo-v2.5',
    provider: 'xiaomi-mimo',
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    supportsVision: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'xiaomi-mimo/mimo-v2.5-pro': {
    // source: fixed missing maxOutputTokens
    id: 'xiaomi-mimo/mimo-v2.5-pro',
    provider: 'xiaomi-mimo',
    contextWindow: 1048576,
    maxOutputTokens: 131072,
    supportsVision: false,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'volcengine/DeepSeek-V4-Pro': {
    // source: modelSpecs.ts:647 deepseek-v4-pro (verb verbatim)
    id: 'volcengine/DeepSeek-V4-Pro',
    provider: 'volcengine',
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    thinkingBudgetCap: 380000,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'zai/glm-4.7-flash': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-4.7-flash',
    provider: 'zai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'zai/glm-5': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5',
    provider: 'zai',
    contextWindow: 200000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 38912,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'zai/glm-5-turbo': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5-turbo',
    provider: 'zai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: false,
  },
  'zai/glm-5.1': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5.1',
    provider: 'zai',
    contextWindow: 200000,
    maxOutputTokens: 128000,
    thinkingBudgetCap: 38912,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'zai/glm-5.2': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5.2',
    provider: 'zai',
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 38912,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'zai/glm-5.2-high': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5.2-high',
    provider: 'zai',
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 38912,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'zai/glm-5.2-max': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5.2-max',
    provider: 'zai',
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 38912,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'zai/glm-5.3': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5.3',
    provider: 'zai',
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 38912,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'zai/glm-5.3-high': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5.3-high',
    provider: 'zai',
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 38912,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
  'zai/glm-5.3-low': {
    // source: fixed missing maxOutputTokens
    id: 'zai/glm-5.3-low',
    provider: 'zai',
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    thinkingBudgetCap: 38912,
    supportsThinking: true,
    supportedParams: new Set<string>(),
    stripParams: new Set<string>(),
    requiresThinkingReconciliation: true,
  },
}

export function getModelSpec(id: string): ModelSpec | undefined {
  const staticSpec = MODEL_REGISTRY[id]
  if (staticSpec) return staticSpec
  const snap = getSyncedSnapshot()
  if (!snap) return undefined
  const synced = snap.get(id)
  if (!synced) return undefined
  // authoritative static already checked, now dynamic fallback
  const provider = id.includes('/')
    ? (id.split('/')[0]?.toLowerCase() ?? 'unknown')
    : 'unknown'
  // For dynamic synced models, derive stripParams as params not in supportedParameters
  // (OpenRouter's supported_parameters is authoritative). This ensures temperature/top_p
  // are stripped when not listed, even though they are in BASE_ALLOWLIST (P8 test).
  const stripCandidates = [
    'temperature',
    'top_p',
    'frequency_penalty',
    'presence_penalty',
    'logprobs',
    'top_logprobs',
    'n',
  ]
  const strip = stripCandidates.filter(
    (p) => !synced.supportedParameters.includes(p),
  )
  return {
    id: synced.id,
    provider,
    contextWindow: synced.contextLength,
    maxOutputTokens: synced.maxCompletionTokens,
    supportedParams: new Set<string>(synced.supportedParameters),
    stripParams: new Set<string>(strip),
    requiresThinkingReconciliation: false,
  }
}
